[package]
name = "catbox"
version = "0.1.0"
authors = ["aaron"]

[[bin]]
doc = false
name = "catbox"
path = "src/main.rs"

[dependencies]
liner = "0.4.2"
uuid = { version = "0.4", features = ["serde", "v4"] }
